## Numpy  stands for numerical python 
- One of the most Importanat libraray for numerical computatioon
- It supports N dimensional array objects 
- It supports Diff. data types
## Using Numpy we can Performs
- Maths & Logical operations on arrays
- Fourier transforms
- Linear Algebra operations
- Random Number Generation


In [6]:
pip list


Package                            Version  
---------------------------------- ---------
alabaster                          0.7.12   
anaconda-client                    1.7.2    
anaconda-navigator                 1.9.7    
anaconda-project                   0.8.3    
asgiref                            3.2.3    
asn1crypto                         1.0.1    
astroid                            2.3.1    
astropy                            3.2.1    
atomicwrites                       1.3.0    
attrs                              19.2.0   
Babel                              2.7.0    
backcall                           0.1.0    
backports.functools-lru-cache      1.5      
backports.os                       0.1.1    
backports.shutil-get-terminal-size 1.0.0    
backports.tempfile                 1.0      
backports.weakref                  1.0.post1
beautifulsoup4                     4.8.0    
bitarray                           1.0.1    
bkcharts                           0.2      
bleach    

In [1]:
import numpy as np

In [2]:
pip show np

Note: you may need to restart the kernel to use updated packages.


# 1. Using np.array method 
- Ordered collection of elements of basic data types of given length
- Syntax: numpy.array(object)

In [3]:
a1=np.array([1,2,3,4,5])

In [4]:
print(a1)

[1 2 3 4 5]


In [5]:
type(a1)

numpy.ndarray

In [6]:
print(a1.dtype)

int32


In [7]:
a2=np.array([1,2,3,4,5,"yogesh"])

In [8]:
print(a2)

['1' '2' '3' '4' '5' 'yogesh']


In [9]:
print(a2.dtype)

<U11


In [10]:
print(type(a2[1]))

<class 'numpy.str_'>


- Array in python is collection of diff. datatype elements 
- All elements are converted to same data type ,i.e. Conversions will be done of lower datatype elements to higher datatype element

In [11]:
array1=np.array([1,2.3,"Hiii"])

In [12]:
print(type(array1.dtype))

<class 'numpy.dtype'>


In [13]:
print(type(array1[0]))
print(type(array1[1]))
print(type(array1[2]))
#print(type(array1[3]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# 2. Generate Array using Linespace 
- numpy.linespace()-return eqyally spaced number within the given range based on the sample number
- Syntax: numpy.linspace(start,stop,num)
- start -start of interval range
- stop -end of interval range
- num - number of sample to be generated

In [14]:
a=np.linspace(0,90,10)
print(a)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [15]:
a=np.linspace(0,90,10,retstep=True)
print(a)

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]), 10.0)


In [16]:
#Create array pf 5 elemenets between 200 to 300
a2=np.linspace(200,300,5,retstep=True)
print(a2)

(array([200., 225., 250., 275., 300.]), 25.0)


# 3. Generate Array using arange() 
- numpy.arange()-return eqyally spaced number within the given range based on the sample number
- Syntax: numpy.linspace(start,stop,step)
- start -start of interval range
- stop -end of interval range
- step - step size of interval

In [17]:
aa=np.arange(0,20)

In [18]:
print(aa)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
a1a=np.arange(0,20,2)
print(a1a)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
# create array from 70 to 50 with 5 diff.
a11=np.arange(70,50,-5)

In [21]:
print(a11)

[70 65 60 55]


# 4. Generate Array using ones() 
- numpy.ones()- returns an array of given shape and typpe filled with ones
- Syntax - numpy.ones(shape.dtype)
- shape- integer or sequence of intergers
- dtype- data type(default:float)


In [22]:
a4=np.ones((6,7),str)
print(a4)
print(type(a4[2][2]))

[['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1' '1' '1']]
<class 'numpy.str_'>


# 5. Generate Array using zeros() 
- numpy.zeros()- returns an array of given shape and typpe filled with zeroes
- Syntax - numpy.zeros(shape.dtype)
- shape - integer or sequence of intergers
- dtype - data type(default:float)


In [23]:
a5=np.zeros((5,5))
print(a5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 6. Generate Array using random.rand() 
- numpy.random.rand()- returns an array of given 
- Syntax - numpy.random.rand(shape)
- shape - integer or sequence of intergers
- dtype - data type(default:float)


In [24]:
# create 1D array of 5 random elements between 0 to 1 
a6=np.random.rand(0,1,5)
print(a6)

[]


In [25]:
# create 1D array of35 random elements between 200 to 150 
a7=np.random.randint(20,150,(7,5))
print(a7)

[[ 75 128  99 126  41]
 [ 73 101  34 111  37]
 [ 84  34  20  88  58]
 [ 43 101  24  84  52]
 [142 136  81 121  76]
 [ 20 115 148  46 114]
 [ 86  65 109  67 124]]


In [26]:
a7.shape

(7, 5)

In [27]:
a8=np.random.randint(20,150,(3))
print(a8)

[128  25 149]


In [28]:
a8.shape

(3,)

# 7. Generate array using logspace()
- numpy.logspace() - returns equally spaced numbers based on log scale
- Syntax - numpy.logspace(start,stop,num,endpoint,base,dtype)
- start, stop
- num - number of sampler to genrate (default:50)
- endpoint - if true ,stop is last sample
- base- basee of the log space (default:10.0)
- dtype- type of output array
- Generate Array of 5 sample with base 10

In [29]:
a11=np.logspace(1,10,5,True,10)
print(a11)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


# Advantages of array 
1. Speed - Array is faster than list
2. Memory Storage- Array takes less memory than list

In [30]:
import time 

In [31]:
start= time.time()
py_list=[i for i in range (100)]
py_list=[i+2 for i in py_list]
stop=time.time()
print(stop-start)

0.001003265380859375


In [32]:
ar=np.array([[1,2,3,4],[2,3,4,5]])
print(ar)

[[1 2 3 4]
 [2 3 4 5]]


reshape - We can change shape of array

In [33]:
ar=np.array([[1,2,3,4],[2,3,4,5]])
print(ar)
print(ar.shape)
b=ar.reshape(4,2)
print(b)
b.shape

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)
[[1 2]
 [3 4]
 [2 3]
 [4 5]]


(4, 2)

In [55]:
c=np.array([[1,2,3],[3,4,5]])

In [56]:
print(c)

[[1 2 3]
 [3 4 5]]


In [72]:
print(c.reshape(3,2))

[[1 2]
 [3 3]
 [4 5]]


In [70]:
b=c.reshape(3,2)
print(b)

[[1 2]
 [3 3]
 [4 5]]


In [74]:
print(np.sum(b,axis=0))

[ 8 10]


In [102]:
a1


array([[1, 2, 3],
       [2, 3, 4]])

In [103]:
a2

array([[3, 2, 1],
       [2, 3, 4]])

In [85]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[1,2,3],[2,3,4]])
print("Addition=", np.add(a1,a2))

Addition= [[2 4 6]
 [4 6 8]]


In [89]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[1,2,3],[2,3,4]])
print("subtract=", np.subtract(a1,a2))

Addition= [[0 0 0]
 [0 0 0]]


In [91]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[1,2,3],[1,2,3]])
print("Addition=", np.add(a1,a2))

Addition= [[2 4 6]
 [3 5 7]]


In [97]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[3,2,1],[2,3,4]])
print("Multiply=", np.multiply(a1,a2))

Addition= [[ 3  4  3]
 [ 4  9 16]]


In [98]:
a1=np.array([[1,2,3],[2,3,4]])
a2=np.array([[3,2,1],[2,3,4]])
print("Divide=", np.divide(a1,a2))

Multiply= [[0.33333333 1.         3.        ]
 [1.         1.         1.        ]]


In [105]:
np.transpose(a1)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [108]:
a3=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])

In [109]:
a3


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [110]:
a4=a3[1:4,:]

In [111]:
a4

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [133]:
p=np.array([[1,2,3,4]])


In [130]:
a4

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [135]:
a5=np.append(z,a4,axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [129]:
a5

array([[1, 1, 2, 3, 4],
       [2, 2, 3, 4, 5],
       [3, 3, 4, 5, 6],
       [4, 4, 5, 6, 7]])

# Matrix
- Rectangular arrangement of number which will have rows and columns


In [139]:
mat1=np.matrix("1,2,3;1,2,3;1,2,3")

In [140]:
mat1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [141]:
mat1.size

9

In [148]:
mat2=np.matrix("1,2,4;1,3,4;2,3,4")

In [149]:
mat2


matrix([[1, 2, 4],
        [1, 3, 4],
        [2, 3, 4]])

In [ ]:
# this will give multiplication according to maths rule

In [150]:
mat3=np.dot(mat1,mat2)

In [151]:
mat3

matrix([[ 9, 17, 24],
        [ 9, 17, 24],
        [ 9, 17, 24]])

In [ ]:
# Thiswill gives multiplication as value

In [152]:
mat4=np.multiply(mat1,mat2)

In [153]:
mat4

matrix([[ 1,  4, 12],
        [ 1,  6, 12],
        [ 2,  6, 12]])

In [154]:
np.remainder(mat1,mat2)

matrix([[0, 0, 3],
        [0, 2, 3],
        [1, 2, 3]], dtype=int32)

# Linear Algebra

In [155]:
mat1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [156]:
mat2

matrix([[1, 2, 4],
        [1, 3, 4],
        [2, 3, 4]])

In [162]:
m3=np.matrix("2,2;1,3")

In [163]:
m3

matrix([[2, 2],
        [1, 3]])

In [164]:
det=np.linalg.det(m3)

In [165]:
det

4.0

In [166]:
rank_mat=np.linalg.matrix_rank(m3)

In [167]:
rank_mat

2

In [168]:
# Inverse of matrix


In [169]:
mat1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [172]:
m3_inv=np.linalg.inv(m3)
m3_inv

matrix([[ 0.75, -0.5 ],
        [-0.25,  0.5 ]])

In [178]:
# Linear Eq.
A=np.matrix("3,1,2;3,2,5;6,7,8")
B=np.matrix("2;-1;3")

In [179]:
print(A)
print(B)

[[3 1 2]
 [3 2 5]
 [6 7 8]]
[[ 2]
 [-1]
 [ 3]]


In [180]:
result=np.linalg.solve(A,B)

In [181]:
result

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])